### ISSUE TITLE
Issues downloading models

### ISSUE THREAD

**Issue by aereimer** [JuergenFleiss/atrain_core#24]
Issues downloading models. all and base fail, but large-v3 works (Using conda env). Error:

(atrain_core_env) C:\>aTrain_core load --model all
C:\anaconda3\envs\atrain_core_env\lib\site-packages\aTrain_core\custom_file_download.py:1145: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\anaconda3\envs\atrain_core_env\lib\site-packages\aTrain_core\custom_file_download.py:1209: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
.gitattributes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.52k/1.52k [00:00<?, ?B/s]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.0/21.0 [00:00<?, ?B/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.31k/2.31k [00:00<?, ?B/s]
gitattributes.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.48k/1.48k [00:00<?, ?B/s]
model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 145M/145M [00:03<00:00, 42.3MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20M/2.20M [00:00<00:00, 37.7MB/s]
vocabulary.txt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 460k/460k [00:00<00:00, 27.7MB/s]
Traceback (most recent call last):
  File "C:\anaconda3\envs\atrain_core_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\anaconda3\envs\atrain_core_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\anaconda3\envs\atrain_core_env\Scripts\aTrain_core.exe\__main__.py", line 7, in <module>
  File "C:\anaconda3\envs\atrain_core_env\lib\site-packages\aTrain_core\cli.py", line 89, in cli
    download_all_models()
  File "C:\anaconda3\envs\atrain_core_env\lib\site-packages\aTrain_core\load_resources.py", line 19, in download_all_models
    get_model(model)
  File "C:\anaconda3\envs\atrain_core_env\lib\site-packages\aTrain_core\load_resources.py", line 75, in get_model
    assert_model_hash(
  File "C:\anaconda3\envs\atrain_core_env\lib\site-packages\aTrain_core\load_resources.py", line 90, in assert_model_hash
    raise AssertionError(
AssertionError: The model folder has been modified and will be deleted automatically.
 Please download model 'base' again if you wish to use it.

**Comment by JuergenFleiss** [comment]
Thanks for letting us know; we will look into it.

**Comment by JuergenFleiss** [comment]
Has been fixed, thanks @andreafooo

**Comment by RenWal** [comment]
I had the same issue today, looks like it's not fixed. I followed the installation instructions from the README and hit the same error:

```
/home/user/src/aTrain/env/lib/python3.10/site-packages/aTrain_core/custom_file_download.py:1145: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/user/src/aTrain/env/lib/python3.10/site-packages/aTrain_core/custom_file_download.py:1209: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
.gitattributes: 100%
README.md: 100%
config.json: 100%
model.bin: 100%
preprocessor_config.json: 100%
tokenizer.json: 100%
vocabulary.json: 100%
Traceback (most recent call last):
  File "/home/user/src/aTrain/env/bin/aTrain_core", line 8, in <module>
    sys.exit(cli())
  File "/home/user/src/aTrain/env/lib/python3.10/site-packages/aTrain_core/cli.py", line 92, in cli
    get_model(args.model)
  File "/home/user/src/aTrain/env/lib/python3.10/site-packages/aTrain_core/load_resources.py", line 75, in get_model
    assert_model_hash(
  File "/home/user/src/aTrain/env/lib/python3.10/site-packages/aTrain_core/load_resources.py", line 90, in assert_model_hash
    raise AssertionError(
AssertionError: The model folder has been modified and will be deleted automatically. 
 Please download model 'large-v3-turbo' again if you wish to use it.
```
