### ISSUE TITLE
Models using different versions?

### ISSUE THREAD

**Issue by jankapunkt** [JuergenFleiss/atrain_core#9]
When transcribing files with `v1.1.0`  and the `tiny` model, we get the following messages:

```
Model was trained with pyannote.audio 0.0.1, yours is 3.2.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.0+cu121. Bad things might happen unless you revert torch to 1.x.
```

It works though. I just wonder if this can cause any yet unexpected issues?

This is our current config:

```
model = 'tiny'
language = 'auto-detect'
device = 'CPU'
speaker_detection = True
num_speakers = 'auto-detect'
compute_type = 'int8'
```

**Comment by JuergenFleiss** [comment]
That comes from pyannote.audio, and from what I get from the discussion over there, this can be safely ignored. See their [issue](https://github.com/pyannote/pyannote-audio/issues/1342) on it.

should actually happen with all whisper models I think, but cannot test right now.
